### PR TITLE
Blog post for the TSC meeting at Siggraph.

### PR DESCRIPTION
**Pull request by bcipriano**

### CODE REVIEW

**Comment by bcipriano** [comment]
@sharifsalah I could probably use some styling tips here -- I'm not quite happy with it especially the where/when sections.

**Comment by sharifsalah** [comment]
Thanks for doing this, it looks great overall. 

Do you think it's worth explaining what folks can expect? i.e. Can anyone come along and suggest an item for the agenda, ask questions, or is it just listening in?

I don't know as I've never attended a session so asking questions that might occur to other readers ;-)

WRT to formatting, there are some general technical writings style recommendations that you can adopt for the blog:

* Use headings (or a heading) to provide structure (instead of the the bold 'When' and 'Where') and remove the colon.
* Introduce each list with a brief sentence and a colon.

So for this example, we could do something like:

## Attending the TSC

To attend the TSC, make a note of the following details in your diary:

**Date:** Wednesday, July 31st, 2019
**Time:** 10:00am to 11:00am (UTC-07:00) America/Los Angeles
**Location:** JW Marriott, Olympic 3

**Comment by bcipriano** [comment]
Ok, I took another pass. Let me know what you think.

I had to add some `<br>` tags to force styling the way I wanted... the site really wanted to render as either a single line or totally separate paragraphs.

**Comment by bcipriano** [comment]
Yeah, that looks better and does match meaning better. Thanks.

**Pull request merged**
