### PR TITLE
Add a issue template

### PR DESCRIPTION
**Pull request by to09**
## Related issue
issue #169

## Summarize your changes
Add an issue template to help users.

### CODE REVIEW

**Comment by sharifsalah** [comment]
Hmmm, strange. It looks like this includes changes to `.github/PULL_REQUEST_TEMPLATE.md` which I think are already merged. 

@bcipriano I tried the rebase trick again but it didn't seem to work for me. Do you want to have a go?

**Comment by bcipriano** [comment]
Rebase didn't work for me either. Though this one looks different -- the "Add PR Template" commit ID doesn't match the commit ID in `master`. Possibly the branch wasn't created from `master`.

@to09 Please try merging `AcademySoftwareFoundation:master` into your branch (`to09:patch-3`) then pushing that branch to your fork. My hope is that fixes the diff in this PR.

**Comment by to09** [comment]
Thanks for the solution, Even I got stuck into it.

**Comment by to09** [comment]
I will change the branch and do PR again.

**Pull request closed without merging**
